### PR TITLE
Get hidpi_factor from the monitor and use it

### LINKED ISSUE #9: IMGUI Display Missing on Certain Portions of Screen
First of all, thank you for this repo- its exactly what I needed after failing in my own attempt to get these libraries to work together.

The problem that I'm having is that on my Ubuntu (x64) installation the IMGUI window shows up and the ball displays as expected, but the contents of the IMGUI window do not draw.
If I move the window around the screen, in certain positions, an area of the IMGUI window does draw, and this portion changes as I slide the window around. Near the bottom left of the ggez window the full IMGUI contents are displayed.

I was able to fix this by setting the line:
    self.imgui.io_mut().display_framebuffer_scale = [2.0, 2.0];
to    
    self.imgui.io_mut().display_framebuffer_scale = [1.0, 1.0];
 
but I was wondering if there is a reason for the scaling here, and whether changing this has some consequences that I should be aware of.

Thank you!

### PR DESCRIPTION
**Pull request by iolivia**
Should fix #9

### CODE REVIEW

**Comment by nsmryan** [comment]
Trying this on my machine, it does appear to work.

The only issue I have now is that I don't think the ggez window dimensions actually need to be scaled by the hidpi_factor. This branch makes the window very tiny, and doubling the dimensions (which is what I assume you see) makes it the normal size.

I guess imgui is effected by  pixel density in a way that ggez is not?

**Comment by iolivia** [comment]
I think you might be right. Looks good on my screen after the latest commit, can you try now? And attach a screenshot just to be sure 😄

**Comment by nsmryan** [comment]
This change looks good to me:
imgui_ggez_screenshot_fix_hidpi

I looked at ggez a bit, and it seems like there are a couple of issues that the project is having with macs.  The issue https://github.com/ggez/ggez/issues/553 mentions dropping mac support, referencing https://github.com/ggez/ggez/issues/587 with a group of issues related to dpi.

**Comment by iolivia** [comment]
thanks @nsmryan! I wonder if this is something that was introduced in 5.0, since we recently upgraded this repo to use the latest ggez. Would be a shame if mac support was dropped 😢 

I'll land this change now!

**Pull request merged**
