### PR TITLE
Rudimentary keyboard support, plus a few opinionated changes

### PR DESCRIPTION
**Pull request by tasgon**
Hello,

While trying to use this to make my own game, I modified the template to allow me to use the keyboard at a basic level. I figured that I'm probably not the only one that could use this, so I put it back in the starter template. Also, I took out some of the example GUI code, replacing it with the built-in [`Ui::show_demo_window`](https://docs.rs/imgui/0.2.1/imgui/struct.Ui.html#method.show_demo_window) function. That is an opinionated change, and I have no problems with undoing it.

So, yeah, basically that.

### CODE REVIEW

**Comment by mkhan45** [comment]
It's worth noting that backspace and arrow keys don't work, at least in sliders.

Other than that, this was pretty helpful for me.

**Comment by tasgon** [comment]
That's strange, in text input boxes I'm having no problems using backspace or the arrow keys.

**Comment by mkhan45** [comment]
I've just tested it with textinputs and I have the same problem. It may be because of the way I'm passing in the string? I'm on Void Linux 5.4.12_1 with dwm, what are you using to test?

**Comment by mkhan45** [comment]
Oops, this is my bad, I double checked and noticed that I'd accidentally deleted the whole block that handles backspace/arrows etc.

**Comment by iolivia** [comment]
thanks so much for this, will have a look soon! 😄

**Comment by iolivia** [comment]
@telastrus thanks again! 🚀

**Pull request merged**
